# Numpy

In [1]:
import numpy as np
lst = [1, 2, 3, 4]
arr = np.array(lst)
type(arr),arr


(numpy.ndarray, array([1, 2, 3, 4]))

In [2]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr = np.ones(2)
arr

array([1., 1.])

In [5]:
arr = np.zeros(2)
arr

array([0., 0.])

In [6]:
arr = np.ones([2,2])
arr

array([[1., 1.],
       [1., 1.]])

In [7]:
arr = np.zeros([3,4])
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
arr = np.linspace(1, 10, 5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [17]:
arr = np.arange(1,31).reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [18]:
arr = np.random.randint(1,100,10)
arr

array([ 8, 19, 77, 88, 30, 95, 40, 27, 59, 33], dtype=int32)

In [19]:
arr = np.random.random(10)
arr

array([0.86811201, 0.01900896, 0.44391588, 0.61783503, 0.87825276,
       0.80837686, 0.33568157, 0.55809728, 0.17361466, 0.15619742])

In [27]:
arr = np.arange(1,61).reshape(6,10)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)
print(arr.size)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]
(6, 10)
2
int64
60


In [31]:
arr = np.arange(1,61).reshape(6,10)
a = arr.T.shape
a

(10, 6)

# Indexing

In [32]:
arr = np.array([1,2,3,4,5])
arr[0:3]

array([1, 2, 3])

In [36]:
arr = np.arange(1,10).reshape(3,3)
arr[1,2]

np.int64(6)

# Slicing

In [38]:
arr = np.arange(1,10).reshape(3,3)
print(arr)
arr[1: , 1: ]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[5, 6],
       [8, 9]])

In [43]:
arr = np.arange(1,10).reshape(3,3)
(arr[1:2, 1:2]).dtype


dtype('int64')

In [44]:
arr = np.arange(225).reshape(3,15,5)
arr

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124],
        [125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134],
        [135, 136, 137, 138, 139],
        [140, 141,

In [53]:
arr = np.random.randint(1,100, size = (2,6,4))
arr


array([[[80, 64, 28, 65],
        [65, 53, 94, 27],
        [65, 15, 20, 55],
        [74, 13,  8, 24],
        [30, 59, 18, 45],
        [65, 98, 31, 99]],

       [[23, 80, 84, 95],
        [53,  7, 96, 85],
        [62, 36, 12, 27],
        [91, 20, 99, 16],
        [70, 57, 93, 55],
        [59, 15, 22, 51]]], dtype=int32)

In [56]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(np.mean(arr1))
print(np.median(arr1))
print(np.std(arr1))
print(np.var(arr1))
arr3 = np.array([3,4,7,5,6,7,8,9])
arr3.argsort()


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
2.0
2.0
0.816496580927726
0.6666666666666666


array([0, 1, 3, 4, 2, 5, 6, 7])